### ISSUE TITLE
Drag and drop doesn't work on OS X web browsers at random

### ISSUE THREAD

**Issue by kode54** [wothke/webpsx#1]
Doesn't seem to work in Safari, Chrome, or Firefox. In Safari, drag works most of the time. In Chrome and Firefox, it simply offers to download the file to my Downloads folder.

**Comment by wothke** [comment]
The browser's default downloading behavior is active whenever the file is dropped outside of the handled drop area (i.e. the  PlayStation image at the bottom). Browsers like Chrome should give you visual feedback via the mousepointer icon: whenever the little '+' disapears then you are over the drop area. (Unfortunately FF does not seem to give a respective built-in indication..)

I've successfully tested the page using FF and Chromium on WinXP - unfortunately I don't have OS X to test with. (Safari might not work due to its use of old WebAudio method names. Also I doubt that will be able to correctly display the page due to the FF/Chrome specific CSS stuff that I am using.). Are you getting any error messages in the developer console?

**Comment by kode54** [comment]
Safari works now, but now it eventually starts looping the last bit of buffer after about 30-60 seconds of playback. Attempting to use the navigation buttons results in a DOM error for trying to use an object which is no longer usable, or something like that.

The freeze itself does not trigger a notice, though.

**Comment by wothke** [comment]
I guess WebAudio is still what you'd need to call an experimental feature.. I cannot reproduce the  above two issues on WinXP (neither in Chrome nor in FF). However Firefox occasionally just stops the playback until the respecive window is switched into the background - at which point the playback resumes (this happens in all of my WebAudio based players). It looks as if some browsers are still just plain buggy.. but from my experience Chromium based browsers run WebAudio stuff very reliably..
